name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  
  build:
   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build image
        run: docker build -t andregondo/porfolio . 

      - name: push image
        run: |
            docker login -u andregondo -p ${{secrets.REGISTRY_PASS}}     
             docker push andregondo/porfolio 